title: "Prof. (Dr.) Meera S. Patel"
description: "Professor & Head, Department of Education, Gujarat University"
theme: jekyll-theme-minimal
logo: /assets/profile.jpg   # Optional: Add profile image in assets folder
show_downloads: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
